[platformio]
src_dir = src
include_dir = include
test_dir = test
extra_configs =
    platformio-*.ini
default_envs =
    xiao-esp32s3-plus-sdmmc4

[env]
build_unflags =
    -std=gnu++11

lib_deps =
    bblanchon/ArduinoJson@^7.4.2

lib_extra_dirs =
    .pio/generated-libs

build_flags =
    -std=gnu++17
    -DAC_CAN_TX_ID=0x383
    -DAC_CAN_RX_ID=0x382
    -DAC_CAN_LOG_ID=0x796
    -DAC_CAN_BOOT_ID=0x2c8
    -DAC_CAN_BITRATE=1000000
    -DAC_TCP_BRIDGE_PORT=39011
    -DAC_SERIAL_BAUD=921600
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER=1
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=1
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -DCONFIG_ASYNC_TCP_STACK_SIZE=8192

[env:xiao-esp32s3-plus]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = seeed_xiao_esp32s3
board_build.variant = XIAO_ESP32S3_Plus
board_build.partitions = partitions_8mb.csv
extra_scripts =
    pre:generate_libsmb2.py
    pre:generate_version_info.py
    pre:generate_web_ui.py
lib_deps =
    ${env.lib_deps}
    https://github.com/ESP32Async/ESPAsyncWebServer
    h2zero/NimBLE-Arduino
monitor_speed = 921600
monitor_eol = LF
monitor_filters = send_on_enter
monitor_echo = yes
upload_speed = 921600
build_flags =
    ${env.build_flags}
    -DAC_CAN_TX_GPIO=1
    -DAC_CAN_RX_GPIO=2
    -DAC_CAN_TIMING=AC_CAN_TIMING_20TQ_SP80


[env:xiao-esp32s3-plus-sdmmc1]
extends = env:xiao-esp32s3-plus
lib_ignore =
build_flags =
    ${env.build_flags}
    -DAC_CAN_TX_GPIO=1
    -DAC_CAN_RX_GPIO=2
    -DAC_CAN_TIMING=AC_CAN_TIMING_20TQ_SP80
    -DAC_STORAGE_SDMMC_ENABLED=1
    -DAC_STORAGE_MAX_OPEN_FILES=8
    -DAC_SDMMC_WIDTH=1
    -DAC_SDMMC_CLK_GPIO=13
    -DAC_SDMMC_CMD_GPIO=11
    -DAC_SDMMC_D0_GPIO=12
    -DAC_SDMMC_FREQ_KHZ=40000

[env:xiao-esp32s3-plus-sdmmc4]
extends = env:xiao-esp32s3-plus
lib_ignore =
build_flags =
    ${env.build_flags}
    -DAC_CAN_TX_GPIO=1
    -DAC_CAN_RX_GPIO=2
    -DAC_CAN_TIMING=AC_CAN_TIMING_20TQ_SP80
    -DAC_STORAGE_SDMMC_ENABLED=1
    -DAC_STORAGE_MAX_OPEN_FILES=8
    -DAC_SDMMC_WIDTH=4
    -DAC_SDMMC_CLK_GPIO=13
    -DAC_SDMMC_CMD_GPIO=11
    -DAC_SDMMC_D0_GPIO=12
    -DAC_SDMMC_D1_GPIO=38
    -DAC_SDMMC_D2_GPIO=39
    -DAC_SDMMC_D3_GPIO=40
    -DAC_SDMMC_FREQ_KHZ=40000

[env:xiao-esp32s3-plus-spisd]
extends = env:xiao-esp32s3-plus
lib_ignore =
build_flags =
    ${env.build_flags}
    -DAC_CAN_TX_GPIO=1
    -DAC_CAN_RX_GPIO=2
    -DAC_CAN_TIMING=AC_CAN_TIMING_20TQ_SP80
    -DAC_STORAGE_SPI_SD_ENABLED=1
    -DAC_STORAGE_MAX_OPEN_FILES=8
    -DAC_SPI_SD_CS_GPIO=10
    -DAC_SPI_SD_SCK_GPIO=13
    -DAC_SPI_SD_MISO_GPIO=12
    -DAC_SPI_SD_MOSI_GPIO=11
