#pragma once

#ifndef AC_ACTION_BUTTON_GPIO
#define AC_ACTION_BUTTON_GPIO -1
#endif

#ifndef AC_ACTION_BUTTON_ACTIVE_LOW
#define AC_ACTION_BUTTON_ACTIVE_LOW 1
#endif

#ifndef AC_ACTION_BUTTON_PULLUP
#define AC_ACTION_BUTTON_PULLUP 1
#endif

#ifndef AC_ACTION_BUTTON_DEBOUNCE_MS
#define AC_ACTION_BUTTON_DEBOUNCE_MS 35
#endif

#ifndef AC_ACTION_BUTTON_LONG_PRESS_MS
#define AC_ACTION_BUTTON_LONG_PRESS_MS 1200
#endif
