#pragma once

#include <stddef.h>
#include <stdint.h>

#include "edf_file_writer.h"

namespace aircannect {

enum class EdfStrFieldSource : uint8_t {
    Custom,
    Derived,
    SettingGet,
    Summary,
};

struct EdfStrFieldMap {
    EdfStrFieldSource source = EdfStrFieldSource::Custom;
    const char *short_tag = nullptr;
};

static constexpr size_t AC_EDF_STR_FIELD_MAP_COUNT = AC_EDF_STR_CRC_SIGNAL;

static constexpr EdfStrFieldMap AC_EDF_STR_FIELD_MAP
    [AC_EDF_STR_FIELD_MAP_COUNT] = {
        {EdfStrFieldSource::Custom, nullptr},      // Date
        {EdfStrFieldSource::Custom, nullptr},      // MaskOn
        {EdfStrFieldSource::Custom, nullptr},      // MaskOff
        {EdfStrFieldSource::Custom, nullptr},      // MaskEvents
        {EdfStrFieldSource::Derived, "PPD"},       // Duration
        {EdfStrFieldSource::SettingGet, "MOP"},    // Mode
        {EdfStrFieldSource::SettingGet, "STP"},
        {EdfStrFieldSource::SettingGet, "IPC"},
        {EdfStrFieldSource::SettingGet, "STU"},
        {EdfStrFieldSource::SettingGet, "MPA"},
        {EdfStrFieldSource::SettingGet, "MPI"},
        {EdfStrFieldSource::SettingGet, "HSP"},
        {EdfStrFieldSource::SettingGet, "HMA"},
        {EdfStrFieldSource::SettingGet, "HMI"},
        {EdfStrFieldSource::SettingGet, "XE0"},
        {EdfStrFieldSource::SettingGet, "XE1"},
        {EdfStrFieldSource::SettingGet, "XE2"},
        {EdfStrFieldSource::SettingGet, "XE3"},
        {EdfStrFieldSource::SettingGet, "XE4"},
        {EdfStrFieldSource::SettingGet, "XE5"},
        {EdfStrFieldSource::SettingGet, "XE6"},
        {EdfStrFieldSource::SettingGet, "XE7"},
        {EdfStrFieldSource::SettingGet, "ZZ3"},
        {EdfStrFieldSource::SettingGet, "ZZ1"},
        {EdfStrFieldSource::SettingGet, "ZZ2"},
        {EdfStrFieldSource::SettingGet, "ZZ4"},
        {EdfStrFieldSource::SettingGet, "ZZ5"},
        {EdfStrFieldSource::SettingGet, "ZZ7"},
        {EdfStrFieldSource::SettingGet, "ZZ8"},
        {EdfStrFieldSource::SettingGet, "ZZ9"},
        {EdfStrFieldSource::SettingGet, "Z10"},
        {EdfStrFieldSource::SettingGet, "Z11"},
        {EdfStrFieldSource::SettingGet, "Z12"},
        {EdfStrFieldSource::SettingGet, "XA3"},
        {EdfStrFieldSource::SettingGet, "XA1"},
        {EdfStrFieldSource::SettingGet, "XA2"},
        {EdfStrFieldSource::SettingGet, "XA6"},
        {EdfStrFieldSource::SettingGet, "XA7"},
        {EdfStrFieldSource::SettingGet, "XA8"},
        {EdfStrFieldSource::SettingGet, "XA9"},
        {EdfStrFieldSource::SettingGet, "XAA"},
        {EdfStrFieldSource::SettingGet, "ZU1"},
        {EdfStrFieldSource::SettingGet, "XAB"},
        {EdfStrFieldSource::SettingGet, "XB0"},
        {EdfStrFieldSource::SettingGet, "XB1"},
        {EdfStrFieldSource::SettingGet, "XB2"},
        {EdfStrFieldSource::SettingGet, "XB4"},
        {EdfStrFieldSource::SettingGet, "XB5"},
        {EdfStrFieldSource::SettingGet, "XB6"},
        {EdfStrFieldSource::SettingGet, "XB7"},
        {EdfStrFieldSource::SettingGet, "XC0"},
        {EdfStrFieldSource::SettingGet, "XC1"},
        {EdfStrFieldSource::SettingGet, "XC2"},
        {EdfStrFieldSource::SettingGet, "XC3"},
        {EdfStrFieldSource::SettingGet, "XD0"},
        {EdfStrFieldSource::SettingGet, "XD1"},
        {EdfStrFieldSource::SettingGet, "XD2"},
        {EdfStrFieldSource::SettingGet, "XD3"},
        {EdfStrFieldSource::SettingGet, "XD4"},
        {EdfStrFieldSource::SettingGet, "AFC"},
        {EdfStrFieldSource::SettingGet, "RMA"},
        {EdfStrFieldSource::SettingGet, "RMT"},
        {EdfStrFieldSource::SettingGet, "EPA"},
        {EdfStrFieldSource::SettingGet, "EPX"},
        {EdfStrFieldSource::SettingGet, "EPR"},
        {EdfStrFieldSource::SettingGet, "EPT"},
        {EdfStrFieldSource::SettingGet, "SST"},
        {EdfStrFieldSource::SettingGet, "ACC"},
        {EdfStrFieldSource::SettingGet, "ABF"},
        {EdfStrFieldSource::SettingGet, "MSK"},
        {EdfStrFieldSource::SettingGet, "TBT"},
        {EdfStrFieldSource::SettingGet, "CCO"},
        {EdfStrFieldSource::SettingGet, "HMX"},
        {EdfStrFieldSource::SettingGet, "HMS"},
        {EdfStrFieldSource::SettingGet, "HTX"},
        {EdfStrFieldSource::SettingGet, "HTS"},
        {EdfStrFieldSource::Summary, "ZHT"},
        {EdfStrFieldSource::Summary, "HUC"},
        {EdfStrFieldSource::Summary, "BP9"},
        {EdfStrFieldSource::Summary, "BP5"},
        {EdfStrFieldSource::Summary, "R95"},
        {EdfStrFieldSource::Summary, "RFM"},
        {EdfStrFieldSource::Summary, "BFM"},
        {EdfStrFieldSource::Summary, "AUM"},
        {EdfStrFieldSource::Summary, "HHE"},
        {EdfStrFieldSource::Summary, "HTE"},
        {EdfStrFieldSource::Summary, "AHM"},
        {EdfStrFieldSource::Summary, "APM"},
        {EdfStrFieldSource::Summary, "SOM"},
        {EdfStrFieldSource::Summary, "SO9"},
        {EdfStrFieldSource::Summary, "SOX"},
        {EdfStrFieldSource::Summary, "SAU"},
        {EdfStrFieldSource::Summary, "VSR"},
        {EdfStrFieldSource::Summary, "VCR"},
        {EdfStrFieldSource::Summary, "MSP"},
        {EdfStrFieldSource::Summary, "PM9"},
        {EdfStrFieldSource::Summary, "PMA"},
        {EdfStrFieldSource::Summary, "PIM"},
        {EdfStrFieldSource::Summary, "PI9"},
        {EdfStrFieldSource::Summary, "PIA"},
        {EdfStrFieldSource::Summary, "PEM"},
        {EdfStrFieldSource::Summary, "PE9"},
        {EdfStrFieldSource::Summary, "PEA"},
        {EdfStrFieldSource::Summary, "LKM"},
        {EdfStrFieldSource::Summary, "LK9"},
        {EdfStrFieldSource::Summary, "LK7"},
        {EdfStrFieldSource::Summary, "LMX"},
        {EdfStrFieldSource::Summary, "VTM"},
        {EdfStrFieldSource::Summary, "VT9"},
        {EdfStrFieldSource::Summary, "VTA"},
        {EdfStrFieldSource::Summary, "RRM"},
        {EdfStrFieldSource::Summary, "RR9"},
        {EdfStrFieldSource::Summary, "RRA"},
        {EdfStrFieldSource::Summary, "TVM"},
        {EdfStrFieldSource::Summary, "TV9"},
        {EdfStrFieldSource::Summary, "TVA"},
        {EdfStrFieldSource::Summary, "VAM"},
        {EdfStrFieldSource::Summary, "VA9"},
        {EdfStrFieldSource::Summary, "VAA"},
        {EdfStrFieldSource::Summary, "IEM"},
        {EdfStrFieldSource::Summary, "IE9"},
        {EdfStrFieldSource::Summary, "IEA"},
        {EdfStrFieldSource::Summary, "ISM"},
        {EdfStrFieldSource::Summary, "IS9"},
        {EdfStrFieldSource::Summary, "ISA"},
        {EdfStrFieldSource::Summary, "AHI"},
        {EdfStrFieldSource::Summary, "HSC"},
        {EdfStrFieldSource::Summary, "ASC"},
        {EdfStrFieldSource::Summary, "CSC"},
        {EdfStrFieldSource::Summary, "OSC"},
        {EdfStrFieldSource::Summary, "USC"},
        {EdfStrFieldSource::Summary, "RCC"},
        {EdfStrFieldSource::Summary, "CSD"},
};

}  // namespace aircannect
